language: php

branches:
  only:
    - master
    - dev

php:
- 7.1

before_script:
- composer self-update
- composer install --no-interaction
- touch database/database.sqlite

script:
- vendor/bin/phpunit --coverage-clover=coverage.xml
