language: php

branches:
  only:
    - master
    - dev

php:
- 7.1

install:
- sudo pip install codecov

before_script:
- composer self-update
- composer install --no-interaction

after_success:
- bash <(curl -s https://codecov.io/bash)

script:
- vendor/bin/phpunit --coverage-clover=coverage.xml
